name: Build LaTeX document
on:
  push:
    branches: [ main, first ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: project.tex
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            project.pdf
            project.log