name: Build LaTeX document
on:
  push:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: project.tex
      - name: Commit report
        run: |
          git config --global user.name 'ciphersmaug'
          git config --global user.email '39407479+ciphersmaug@users.noreply.github.com'
          git add project.pdf project.log
          git commit -am "Automated report"
          git push